
version: '2'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  api:
    build: ./
    ports:
      - "8080:8080"
    links:
      - redis
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./src:/usr/src/app/src
